/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IntervalRefreshRouteImport } from "./routes/interval-refresh"
import { Route as IndexRouteImport } from "./routes/index"

const IntervalRefreshRoute = IntervalRefreshRouteImport.update({
  id: "/interval-refresh",
  path: "/interval-refresh",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/interval-refresh": typeof IntervalRefreshRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/interval-refresh": typeof IntervalRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/interval-refresh": typeof IntervalRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/interval-refresh"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/interval-refresh"
  id: "__root__" | "/" | "/interval-refresh"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntervalRefreshRoute: typeof IntervalRefreshRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/interval-refresh": {
      id: "/interval-refresh"
      path: "/interval-refresh"
      fullPath: "/interval-refresh"
      preLoaderRoute: typeof IntervalRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntervalRefreshRoute: IntervalRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
