/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as QrcodeGeneratorImport } from "./routes/qrcode-generator"
import { Route as IntervalRefreshImport } from "./routes/interval-refresh"
import { Route as IndexImport } from "./routes/index"

// Create/Update Routes

const QrcodeGeneratorRoute = QrcodeGeneratorImport.update({
  id: "/qrcode-generator",
  path: "/qrcode-generator",
  getParentRoute: () => rootRoute,
} as any)

const IntervalRefreshRoute = IntervalRefreshImport.update({
  id: "/interval-refresh",
  path: "/interval-refresh",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/interval-refresh": {
      id: "/interval-refresh"
      path: "/interval-refresh"
      fullPath: "/interval-refresh"
      preLoaderRoute: typeof IntervalRefreshImport
      parentRoute: typeof rootRoute
    }
    "/qrcode-generator": {
      id: "/qrcode-generator"
      path: "/qrcode-generator"
      fullPath: "/qrcode-generator"
      preLoaderRoute: typeof QrcodeGeneratorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/interval-refresh": typeof IntervalRefreshRoute
  "/qrcode-generator": typeof QrcodeGeneratorRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/interval-refresh": typeof IntervalRefreshRoute
  "/qrcode-generator": typeof QrcodeGeneratorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/interval-refresh": typeof IntervalRefreshRoute
  "/qrcode-generator": typeof QrcodeGeneratorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/interval-refresh" | "/qrcode-generator"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/interval-refresh" | "/qrcode-generator"
  id: "__root__" | "/" | "/interval-refresh" | "/qrcode-generator"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntervalRefreshRoute: typeof IntervalRefreshRoute
  QrcodeGeneratorRoute: typeof QrcodeGeneratorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntervalRefreshRoute: IntervalRefreshRoute,
  QrcodeGeneratorRoute: QrcodeGeneratorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/interval-refresh",
        "/qrcode-generator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/interval-refresh": {
      "filePath": "interval-refresh.tsx"
    },
    "/qrcode-generator": {
      "filePath": "qrcode-generator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
