/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IntervalRefreshImport } from "./routes/interval-refresh"
import { Route as ChessImport } from "./routes/chess"
import { Route as IndexImport } from "./routes/index"

// Create/Update Routes

const IntervalRefreshRoute = IntervalRefreshImport.update({
  id: "/interval-refresh",
  path: "/interval-refresh",
  getParentRoute: () => rootRoute,
} as any)

const ChessRoute = ChessImport.update({
  id: "/chess",
  path: "/chess",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/chess": {
      id: "/chess"
      path: "/chess"
      fullPath: "/chess"
      preLoaderRoute: typeof ChessImport
      parentRoute: typeof rootRoute
    }
    "/interval-refresh": {
      id: "/interval-refresh"
      path: "/interval-refresh"
      fullPath: "/interval-refresh"
      preLoaderRoute: typeof IntervalRefreshImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/chess": typeof ChessRoute
  "/interval-refresh": typeof IntervalRefreshRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/chess": typeof ChessRoute
  "/interval-refresh": typeof IntervalRefreshRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/chess": typeof ChessRoute
  "/interval-refresh": typeof IntervalRefreshRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/chess" | "/interval-refresh"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/chess" | "/interval-refresh"
  id: "__root__" | "/" | "/chess" | "/interval-refresh"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChessRoute: typeof ChessRoute
  IntervalRefreshRoute: typeof IntervalRefreshRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChessRoute: ChessRoute,
  IntervalRefreshRoute: IntervalRefreshRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chess",
        "/interval-refresh"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chess": {
      "filePath": "chess.tsx"
    },
    "/interval-refresh": {
      "filePath": "interval-refresh.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
